name: Movieo CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Build & Test All Projects
    runs-on: ubuntu-latest
    continue-on-error: false

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: movieo_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/movieo_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 20.9
        uses: actions/setup-node@v3
        with:
          node-version: 20.9

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Generate Prisma client
        working-directory: ./server
        run: npx prisma generate

      - name: Apply Prisma migrations
        working-directory: ./server
        run: npx prisma migrate deploy

      - name: Lint server code
        working-directory: ./server
        run: npm run lint

      - name: Type check server code
        working-directory: ./server
        run: npm run typecheck

      - name: Run server tests
        working-directory: ./server
        run: npm test

      - name: Build server project
        working-directory: ./server
        run: npm run build

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Lint client code
        working-directory: ./client
        run: npm run lint

      - name: Type check client code
        working-directory: ./client
        run: npm run typecheck

      - name: Run client tests
        working-directory: ./client
        run: npm test

      - name: Build client project
        working-directory: ./client
        run: npm run build
